export const BOOKSHELF_LIST_REQUEST = 'BOOKSHELF_LIST_REQUEST';
export const BOOKSHELF_LIST_SUCCESS = 'BOOKSHELF_LIST_SUCCESS';
export const BOOKSHELF_LIST_FAIL = 'BOOKSHELF_LIST_FAIL';

export const ALL_BOOKSHELF_LIST_REQUEST = 'ALL_BOOKSHELF_LIST_REQUEST';
export const ALL_BOOKSHELF_LIST_SUCCESS = 'ALL_BOOKSHELF_LIST_SUCCESS';
export const ALL_BOOKSHELF_LIST_FAIL = 'ALL_BOOKSHELF_LIST_FAIL';
